name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 自動執行

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub Contribution

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SVG
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          username: lin20031018

      - name: Push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "update 3D contribution graph" || echo "No changes to commit"
          git push
