name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 執行一次

jobs:
  build:
    name: Generate 3D GitHub Contribution
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate 3D Graph using forked action
        uses: n8n-io/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "update 3D contribution graph" || echo "no changes"
          git push
