name: Build 3D Contribution Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 自動執行一次

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 重要！否則無法 push 圖片

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build 3D SVGs
        run: npm run build

      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "Update 3D contribution graph" || echo "No changes to commit"
          git push

